name: Ajouter une citation
description: Vous ne trouvez pas votre citation préférée ? Ajoutez-la !
title: "[Quote]: "
labels: [new_quote]
assignees:
  - tangimds
body:
  - type: input
    id: contact
    attributes:
      label: Infos contact
      description: Et si on a besoin de plus d'infos ?
      placeholder: ex. culdechouette@kammelott.com
    validations:
      required: false
  - type: textarea
    id: quote
    attributes:
      label: La citation
      description: Une ou deux phrase, c'est parfait !
      placeholder: Ce que je dis, tout le monde s'en tamponne ! Je gueule, je gueule, j'pourrais gueuler dans le cul d'un poney ce serait pareil !
    validations:
      required: true
  - type: dropdown
    id: season
    attributes:
      label: Livre
      description: Savez-vous dans quel Livre cette citation est entendue pour la première fois ?
      options:
        - Livre I
        - Livre II
        - Livre III
        - Livre IV
        - Livre V
        - Livre VI
    validations:
      required: false
  - type: input
    id: episode
    attributes:
      label: Épisode
      description: Savez-vous dans quel épisode cette citation est entendue pour la première fois ?
      placeholder: "23 : La révolte"
    validations:
      required: false
  - type: dropdown
    id: actor
    attributes:
      label: Acteur
      description: Quel est l'acteur en scène ?
      options:
        - lui
    validations:
      required: true
  - type: dropdown
    id: character
    attributes:
      label: Personnage
      description: Quel est le personnage en scène ?
      options:
        - lui
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Auteur
      description: Qui est le génie derrière cette prose ?
      placeholder: Alexandre Astier
      value: Alexandre Astier
    validations:
      required: true
  - type: input
    id: series
    attributes:
      label: Série
      placeholder: Kaamelott
      value: Kaamelott
    validations:
      required: true
