name: Ajouter une citation
description: Vous ne trouvez pas votre citation préférée ? Ajoutez-la !
labels: [new_quote]
assignees:
  - tangimds
body:
  - type: input
    id: contact
    attributes:
      label: Infos contact
      description: Et si on a besoin de plus d'infos ?
      placeholder: ex. culdechouette@kammelott.com
    validations:
      required: false
  - type: textarea
    id: quote
    attributes:
      label: La citation
      description: Une ou deux phrase, c'est parfait !
      placeholder: Ce que je dis, tout le monde s'en tamponne ! Je gueule, je gueule, j'pourrais gueuler dans le cul d'un poney ce serait pareil !
    validations:
      required: true
  - type: dropdown
    id: season
    attributes:
      label: Livre
      description: Savez-vous dans quel Livre cette citation est entendue pour la première fois ?
      options:
        - Livre I
        - Livre II
        - Livre III
        - Livre IV
        - Livre V
        - Livre VI
    validations:
      required: false
  - type: input
    id: episode
    attributes:
      label: Épisode
      description: Savez-vous dans quel épisode cette citation est entendue pour la première fois ?
      placeholder: "23 : La révolte"
    validations:
      required: false
  - type: dropdown
    id: actor
    attributes:
      label: Acteur
      description: Quel est l'acteur en scène ?
      options:
        - Alexandre Astier
        - Lionnel Astier
        - Franck Pitiot
        - Jean-Christophe Hembert
        - Anne Girouard
        - Thomas Cousseau
        - Nicolas Gabion
        - Jean-Robert Lombard
        - Joëlle Sevilla
        - Jacques Chambon
        - Audrey Fleurot
        - Simon Astier
        - Stéphane Margot
        - Brice Fournier
        - Aurélien Portehaut
        - Caroline Ferrus
        - Alain Chapuis
        - Alexis Hénon
        - Tony Saba
        - Loïc Varraut
        - Caroline Pascal
        - Christian Bujeau
        - Serge Papagalli
        - François Rollin
        - Bruno Fontaine
        - Vanessa Guedj
        - Josée Drevon
        - Gilles Graveleau
        - Antoine de Caunes
        - Carlo Brandt
        - Valérie Benguigui
        - Thibault Roux
        - Etienne Fague
        - Pierre Mondy
        - Emmanuel Meirieu
        - Tcheky Karyo
        - Valeria Cavalli
        - Pascal Vincent
        - Georges Beller
        - Bruno Salomone
        - Guillaume Briat
        - Manu Payet
        - Pascal Demolon
        - Axelle Laffont
        - Patrick Chesnais
        - Christian Clavier
        - Loránt Deutsch
        - Philippe Nahon
        - Émilie Dequenne
        - Alain Chabat
        - François Levantal
        - Claire Nadeau
        - Yvan le Bolloc'h
        - Lan Truong
        - Anouk Grinberg
        - Alexandra Saadoun et Magali Saadoun
        - François Morel
        - Anne Benoît
    validations:
      required: true
  - type: dropdown
    id: character
    attributes:
      label: Personnage
      description: Quel est le personnage en scène ?
      options:
        - Arthur
        - Léodagan de Carmélide
        - Perceval de Galles
        - Karadoc de Vannes
        - Guenièvre
        - Lancelot du Lac
        - Bohort de Gaunes
        - Père Blaise
        - Séli
        - Merlin
        - La Dame du Lac
        - Yvain, chevalier au Lion
        - Calogrenant
        - Kadoc
        - Gauvain, chevalier au Pancréas
        - Mevanwi
        - Le tavernier
        - Galessin
        - Hervé de Rinel
        - Venec
        - Demetra
        - Maître d’armes
        - Guethenoc
        - Loth
        - Élias de Kelliwic'h
        - Angharad
        - Ygerne de Tintagel
        - Roparzh
        - Dagonet
        - Méléagant
        - Prisca
        - Grüdü
        - Lionel de Gaunes
        - César
        - Appius Manilius
        - Manius Macrinus Firmus
        - Aconia Minor
        - Urgan
        - Jacca
        - Caius Camillus
        - Le roi Burgonde
        - Verinus
        - Spurius Cordius Frontinius
        - Séfriane d'Aquitaine
        - Lucius Silius Sallustius
        - Jurisconsulte
        - l'interprète
        - Goustan de Carmélide
        - Edern
        - Le Duc d'Aquitaine
        - Publius Servius Capito
        - Cryda de Tintagel
        - Breccan
        - Attila
        - Anna de Tintagel
        - Les jumelles du pêcheur
        - Belt
        - Drusilla
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Auteur
      description: Qui est le génie derrière cette prose ?
      placeholder: Alexandre Astier
      value: Alexandre Astier
    validations:
      required: true
  - type: input
    id: series
    attributes:
      label: Série
      placeholder: Kaamelott
      value: Kaamelott
    validations:
      required: true
